apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/actual-budget/data"