apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: actual-budget