apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluetun-config-pv
  labels: 
    app: gluetun
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/gluetun/config"
  storageClassName: ""