apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
  labels: 
    app: qbittorrent
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/qbittorrent/config"
  storageClassName: ""