
replicaCount: 2

image:
  tag: ""

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.50
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceWeb:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.50
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    # virtualHost (default value is pi.hole) will be appended to the hosts
    - pihole-k8s.local

persistentVolumeClaim:
  enabled: true
  existingClaim: "pihole-config"

# I allow pihole replica on my media server as DNS is critical
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "media-server"
  effect: "NoSchedule"

adminPassword: "changeme"

DNS1: "1.1.1.2"
DNS2: "1.0.0.2"

doh:
  enabled: true
  pullPolicy: Always
  # -- Here you can pass environment variables to the DoH container, for example:
  envVars:
    TUNNEL_DNS_UPSTREAM: "https://1.1.1.2/dns-query,https://1.0.0.2/dns-query"

dnsmasq:
  customDnsEntries:
    - address=/.local/10.0.0.32

# If you setup monitoring
podAnnotations:
  prometheus.io/port: '9617'
  prometheus.io/scrape: 'true'

monitoring:
  sidecar:
    enabled: true

podDnsConfig:
  enabled: true
  policy: "None"
  nameservers:
    - 127.0.0.1
    - 1.1.1.2