apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: pihole-config