apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pihole/config"